CREATE DataBase DiplomskiRad

CREATE TABLE PREDMET
(
	ID_PREDMETA INT IDENTITY(1,1) PRIMARY KEY,
	NAZIV_PREDMETA VARCHAR(30) NOT NULL
)

CREATE TABLE SMER
(
	ID_SMERA INT IDENTITY(1,1) PRIMARY KEY,
	NAZIV_SMERA VARCHAR(20) NOT NULL,
	BROJ_STUDENTA INT
	
)

CREATE TABLE STUDENT
(
	EMAIL VARCHAR(40) PRIMARY KEY,
	PASSWORD VARCHAR(40) NOT NULL,
	JMBG BIGINT NOT NULL,
	IME VARCHAR(20) NOT NULL,
	PREZIME VARCHAR(28) NOT NULL,
	NIVO_STUDIJA VARCHAR(32) NOT NULL,
	BR_INDEKSA BIGINT NOT NULL,
	ULICA VARCHAR(30),
	BROJ INT,
	DATUM_UPISA DATE NOT NULL,
	ID_SMERA INT NOT NULL,
	CONSTRAINT SMER_FK FOREIGN KEY (ID_SMERA)
	REFERENCES SMER(ID_SMERA)
)
CREATE TABLE ZAPOSLEN
(
	EMAIL VARCHAR(40) PRIMARY KEY,
	PASSWORD VARCHAR(40) NOT NULL,
	JMBG BIGINT NOT NULL,
	L_IME VARCHAR(12) NOT NULL,
	IME_RODITELJA VARCHAR(12) NOT NULL,
	PREZIME VARCHAR(18) NOT NULL,
	DATUM_RODJENJA DATE,
	ULICA VARCHAR(18),
	BROJ INT,
	TIP_OSOBLJA VARCHAR(20) NOT NULL,
	STRUCNA_SPREMA VARCHAR(20)
)
CREATE TABLE DIPLOMSKI_RAD
(
	ID_DIPLOMSKI INT IDENTITY(1,1) PRIMARY KEY,
	OCENA INT CONSTRAINT DIP_CK CHECK (OCENA BETWEEN 5 AND 10),
	NAZIV_TEME VARCHAR(50),
	DATUM_ODBRANE DATE NOT NULL ,
	EMAIL_STUD VARCHAR(40) ,
	EMAIL_NAS VARCHAR(40) ,
	ID_PREDMETA INT ,
	CONSTRAINT STUDENT1_FK FOREIGN KEY (EMAIL_STUD)
	REFERENCES STUDENT(EMAIL),
	CONSTRAINT ZAPOSLEN11_FK FOREIGN KEY (EMAIL_NAS)
	REFERENCES ZAPOSLEN(EMAIL),
	CONSTRAINT PREDMET1_FK FOREIGN KEY (ID_PREDMETA)
	REFERENCES PREDMET(ID_PREDMETA)
)

CREATE TABLE ANGAZOVAN_NA
(
	ID_ANGAZOVAN INT IDENTITY(1,1) PRIMARY KEY,
	EMAIL_NASTAVNIKA VARCHAR(40) NOT NULL,
	ID_PREDMETA INT NOT NULL,
	DATUM_ANGAZOVANJA DATE,
	CONSTRAINT ZAPOSLEN_FK FOREIGN KEY(EMAIL_NASTAVNIKA)
	REFERENCES ZAPOSLEN(EMAIL),
	CONSTRAINT PREDMET_FK FOREIGN KEY(ID_PREDMETA)
	REFERENCES PREDMET(ID_PREDMETA)
)

CREATE TABLE UCI_NA
(
	ID_UCI_NA INT IDENTITY(1,1) PRIMARY KEY,
	ID_SMERA INT NOT NULL,
	ID_PREDMETA INT NOT NULL,
	CONSTRAINT SMERR_FK FOREIGN KEY(ID_SMERA)
	REFERENCES SMER(ID_SMERA),
	CONSTRAINT PREDMETT_FK FOREIGN KEY(ID_PREDMETA)
	REFERENCES PREDMET(ID_PREDMETA)
)

CREATE TABLE TELEFON_Z
(
	ID_TELEFONA INT IDENTITY(1,1) PRIMARY KEY,
	TELEFON INT NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	CONSTRAINT ZAPOSLEN2_FK FOREIGN KEY(EMAIL)
	REFERENCES ZAPOSLEN(EMAIL)
)


CREATE TABLE TELEFON_S
(
	ID_TELEFONA INT IDENTITY(1,1) PRIMARY KEY,
	TELEFON INT NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	CONSTRAINT STUDENT2_FK FOREIGN KEY(EMAIL)
	REFERENCES STUDENT(EMAIL)
)


CREATE TABLE GODINE
(
	ID_GODINE INT IDENTITY(1,1) PRIMARY KEY,
	GODINA INT CONSTRAINT GOD_CK CHECK (GODINA BETWEEN 1 AND 4),
	ID_PREDMETA INT NOT NULL,
	CONSTRAINT PREDMET111_FK FOREIGN KEY(ID_PREDMETA)
	REFERENCES PREDMET(ID_PREDMETA)
	
)